### ISSUE TITLE
Returns only 50 results from a list of 124 items

### ISSUE THREAD

**Issue by nate2014jatc** [ThatGuySam/youtube-playlist-json#1]
Playlist `PLQvCb0odWC4zJJrKvqYoI2kTHQBwFzsl1` has 124 items.
The JSON output of the tool reports 50 items. (attached below as a TXT as GH doesn't allow JSON files for some reason)

[PLQvCb0odWC4zJJrKvqYoI2kTHQBwFzsl1.txt](https://github.com/ThatGuySam/youtube-playlist-json/files/2799130/PLQvCb0odWC4zJJrKvqYoI2kTHQBwFzsl1.txt)

**Comment by ThatGuySam** [comment]
That's probably the default paging size for youtube's responses, which means the rest of your playlist is on pages 2 and 3. 

Unfortunately, I don't have a ton of time to work on this repo but if you want, feel free to fork the repo and build a paging feature of your own, I'd be glad integrate it. 

Here's Youtube's documentation on it:
https://developers.google.com/youtube/v3/docs/playlistItems/list

**Comment by ThatGuySam** [comment]
Hey, I have good news! 

I build a new version of this library that gets all of the items and caches the result so you shouldn't get rate limited by Google. 

https://github.com/ThatGuySam/youtube-json-server

Let me know if it works for you.
